### ISSUE TITLE
npx shadxn registry init

### ISSUE THREAD

**Issue by saifelarbi** [anis-marrouchi/shadxn#3]
Hello there,
Thank you for this nice project. I have followed the Getting started article and have encountered the following error when run the npx shadxn registry init to intialize my custom registry.
I’m on Windows 10, running the command from Bash 
Node v20.10.0
Npm 10.2.3

![image](https://github.com/anis-marrouchi/shadxn/assets/57010439/ff8b5aa1-b982-40e3-8d11-4a33b724c5fa)

**Comment by saifelarbi** [comment]
I have tried with 
`npm cache clean --force`

**Comment by anis-marrouchi** [comment]
Hi there @saifelarbi and thank you for reporting this issue. Do you mind pasting the error to the message

**Comment by saifelarbi** [comment]
@anis-marrouchi 

`$ npx shadxn registry init
Initializing registry...
❌ Error initializing registry: [Error: ENOENT: no such file or directory, lstat 'C:\C:\Users\hp%20820\AppData\Local\npm-cache\_npx\bb3f3599210e9ad8\node_modules\shadxn\src\registries\shadxn'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'C:\\C:\\Users\\hp%20820\\AppData\\Local\\npm-cache\\_npx\\bb3f3599210e9ad8\\node_modules\\shadxn\\src\\registries\\shadxn'
}`

**Comment by anis-marrouchi** [comment]
I don't have a Windows machine at the moment, would like to contribute on this issue?
