### ISSUE TITLE
Error when run shadxn registry build

### ISSUE THREAD

**Issue by saifelarbi** [anis-marrouchi/shadxn#5]
Hello,
I m running on Windows **shadxn registry build** ,
I have run the shadxn registry init to initialize my custom registry,
Before adding my reusable components to the registry folder I’ve tried to build the registry using the default components that comes with the command an the error below happens .
```
Building registry for Next.js project...
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader.
On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

**Comment by anis-marrouchi** [comment]
Hi @saifelarbi,
Thanks for reporting the issue. This is due to how Windows handles file path. UsingpathToFileURL } from 'url' module might fix the problem. Would you like to contribute and fix it?
